# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactInstance',
            new_name='Post',
        ),
    ]
